version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:18.04
    steps:
      - checkout
      - run: sh ./build.sh -s
  test:
    docker:
      - image: buildpack-deps:18.04
    steps:
      - checkout
      - run: sh ./build.sh -s test
  coverage:
    docker:
      - image: buildpack-deps:18.04
    steps:
      - checkout
      - run: sh ./build.sh -s cov
      - run: bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
  coverage:
    jobs:
      - coverage
